import React from 'react';
import Head from 'next/head';
import { Heebo } from '@next/font/google';
import { styled } from './styles';

const heebo = Heebo({ subsets: ['latin'] });
const Button = styled('button', {
  backgroundColor: '$blue500',
  borderRadius: 5,
  border: 'none',
  cursor: 'pointer',
  padding: '10px 15px',
  color: '$gray100'
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Luxury Mobile Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={heebo.className}>Luxury Mobile Store</h1>
      <Button className={heebo.className}>Buy Phone</Button>
    </>
  );
}
